FROM ft-rails:on-build

EXPOSE 3000

CMD ["rails", "s", "-b", "0.0.0.0", "-p", "3000"]

#use docker build -t crisrubyby .
#docker run -it --rm -p 3000:3000 crisrubyby:latest
#go to http://192.168.99.112:3000/